zurg: ENC[AES256_GCM,data:kJc=,iv:5Bnw3W3RYtjsxW5Uy+4gdVRiQhx5ifoDoFmttw0syIY=,tag:20d1kY5GAoxQIYdrcVFOPw==,type:str]
token: ENC[AES256_GCM,data:lRVMBtnH0W0VGf/YrRdxLkJxmuaXbhSHtPWXPRoKuuuUmmlnfuKlt7YI+ZvHsOQve7G3Mg==,iv:BaIE1KJUOHQh+XJbCtoBYEImm9oMWTMgxi5ocgkQH3Y=,tag:619Ot7J/TNdIoWidQnOjfA==,type:str]
#ENC[AES256_GCM,data:sSz2ZWqM33x1MhZcFA==,iv:qAZJPj01lh68xJrkbiNcXKslglZsPsveG5qEL8z6ujg=,tag:PRyt8v8Uqb9mzvzb4hKFOA==,type:comment]
#ENC[AES256_GCM,data:oVTrI5k7tzdLP9k=,iv:Oo/4+a7AoUxSxZqcL0m9W6FW3rVlGVh5YWiU8/5f48E=,tag:WOP2sgFQVyOroGQ+FmABVw==,type:comment]
#ENC[AES256_GCM,data:4Pgl/Y7/7t4dUw==,iv:u3eTSdvJBEOuUs6LTjH2iZm0p374AjHgUSUJslSoazg=,tag:t9K9AWST6DgdAWRYv87Eiw==,type:comment]
#ENC[AES256_GCM,data:OtqM+lgw8rxVfQ==,iv:UihEIH61Q0AQ4mfpNryrzLYREzKLgLVbrijX4G9rt3U=,tag:NMBpBXNvaRNpZtvFSCFw3Q==,type:comment]
#ENC[AES256_GCM,data:Xqe1uhqbCg==,iv:VK0NCNoVQO13MysxiniBEBOdy4fTM684yaEmCApXGGo=,tag:yBbUu8YV+8fUCIwilfq7Fw==,type:comment]
#ENC[AES256_GCM,data:f4CmWnm7VEP6n3mvlyGW1R0kCacNt6o=,iv:czGtXio+kHlwEq8VRmn1rA08h3BcIZccShIoda0iCrc=,tag:RHqfoYmLuNy/Rt3ICklZrQ==,type:comment]
check_for_changes_every_secs: ENC[AES256_GCM,data:wco=,iv:Wj8Pofq9EQZ+kEzFfzIVm7KzbVYsjHWAWSJT3wwlsJo=,tag:rEs/6YY8/PywTsayiJYZsg==,type:int]
#ENC[AES256_GCM,data:Y+QiPx4PaXxQzS64zBMqkrn2ADPY/g==,iv:ndJ5ZIQUlD0ZaIZFGzj18bPaW6inK2wLfm0w+OhnNdA=,tag:C99NrRx5X+4UFds/ZKjjlQ==,type:comment]
#ENC[AES256_GCM,data:j3OOmtTVuGORqvQyry1qKiOLjZ6+lQ==,iv:HT9gOiO7A84uzsepDEGE0WHMEMrgaY8zypVQCCDeVDg=,tag:rDTZ+MmQPTIM2A4ojJoxvA==,type:comment]
#ENC[AES256_GCM,data:1/ufRwZJ/Mmp6aQSE6L8JdKhXcsulrrniXthnidp,iv:Kp/zn9EOcmZ7EQWG9cg1j2X8d7bKzwaqQcqAwwQUeec=,tag:a7ThXFPlDB7VXcYP9/suFQ==,type:comment]
#ENC[AES256_GCM,data:+a7UzBbJ6MTOyWkGpJwUSG0PccQbRfVzwPZksQZKJXGwxYla,iv:SidJ+DfjxOpcbxcfckQIV6sGaWOxEdwWXqwA12kCPo0=,tag:0eK9fvntOH95oqAjiXL8WQ==,type:comment]
enable_repair: ENC[AES256_GCM,data:cDPRqw==,iv:Ryg65zKyvFAupvc9PlWIEardYH4fHK6pkpiM+UpBaW4=,tag:rSwdqQDS42dgdfScRWc3JA==,type:bool]
auto_delete_rar_torrents: ENC[AES256_GCM,data:1wx1pA==,iv:vhNhIVwV8bHBcOxbNwfjWQn4ac5RMs3yTEVo2BqX1Uc=,tag:YquqBQz5eu7kek9O8Vd0PQ==,type:bool]
#ENC[AES256_GCM,data:UlaEpIWNgDWeZoTN1MJ1s3M0KPhW,iv:tDinSPwZD83oSbPwlg2eXBPPFGWikAVxLpCJCiz45sQ=,tag:lSkb0Qk1mywMWqC+A75nOA==,type:comment]
#ENC[AES256_GCM,data:/QnjOlHDHLGfKzMKkWm2fA08y9e+FwvXi4g=,iv:dH0A6zKpElh/xBOLOdxUuUBTPjD8lorIP4DG/5P3R1w=,tag:mBbbARBMJUW+srqZWSbRrw==,type:comment]
#ENC[AES256_GCM,data:/Ok+AipQ2gTBW/nEAFDi+XuuPhQ3EQ4jRmX/Ep4=,iv:gh5v5dgm88+iiEerjL7BAWx6e2AHnDsSJQOj8oHm7Tc=,tag:90qSNbfgfpmtW3xBcfCsGg==,type:comment]
#ENC[AES256_GCM,data:59mxkoLc/GrJ91GztGG82Ay6Uw5pUm631A==,iv:s30zldgNRGMcc2w7EZzn+bmYQMPmUchgLlTsxyhnzds=,tag:44ZxzkqGjKIAov1Wfxe5GA==,type:comment]
#ENC[AES256_GCM,data:+C1ycbeWNrknnWfVjtVUWz82rH2qSZ3c,iv:MTzhH4V/Pwmc0jZdJAN8mLk17Ot/EHcihEJEFJgywmY=,tag:8GNKhPg1cnZHfWRHuNm+Uw==,type:comment]
#ENC[AES256_GCM,data:mVLxW7kMkGX3iO08DUIqO0x6wIf54a0NpuAA6lPa6LzD3lI=,iv:kijpPmduehCEhJ5im8yzihVCHApMAInqfCwyoo2ILIU=,tag:rLlJfULXkm00KnN4j/qpRg==,type:comment]
#ENC[AES256_GCM,data:/DfF/N6/7RpKQkk3aapNJMtiMXmAc0rxeA==,iv:9YzhSoBweQzSm4bu7CB1A11HviarbRcm75nexn30DE4=,tag:O8g1ygs2LVsqdiwD6kmUxw==,type:comment]
#ENC[AES256_GCM,data:VrLy3Zso8jq0Hxjg+YvZY7u8XM1ZN9bacNsV2Q==,iv:8eMt7nqDk7wVkMicYA/nrG/Db/BXMZN00y+tAKHHsCs=,tag:sBa8NY7MqgZz+7x+wyQpwA==,type:comment]
#ENC[AES256_GCM,data:CIdbWnSulS5lKrC+EWOsYRel,iv:SOxBIndEPyBfzdA7V1moGNzT3MKqvqdaFAYPzbgtTNk=,tag:CVfq2KkG0OSGAl/JenoJTA==,type:comment]
on_library_update: ENC[AES256_GCM,data:t2bd4aqgSoL5+epQBSdIqYgKpWhYju7/piQ=,iv:9n4+6JH5BroVnhHem1pRalko+Am/AE/+qLftdeLNSbc=,tag:oiHP/M1cGvsWEn7x+QG/gQ==,type:str]
#ENC[AES256_GCM,data:O4Lzepr2aWbQ+pb8Id18hx2OiqAokyFqcEut3fYEy39qaaGu5tSU6zQVaK6jEvBbpBpdoIAzO2V/OhyopFi10w==,iv:05Uq6zKCt9wUGantHUxHHNMWQvt/+kBFX5/V2+p2DDc=,tag:47qem7Yfnk/YqBTQZHOHyQ==,type:comment]
#ENC[AES256_GCM,data:Rk2XjB3MuL9cRWRpQQVLEc7gP9ppeVbwXu9NB7PmWFE+t7l9fANchBjIXV4gkEAuXqhkI50VuznuMYe4NjNo6zQrxYHfh81H+fIKTPOLnCLM9JUUjD1XDNCUfcsa,iv:h4SXJ2wKwjUn9hetVnyhOAktCr7mX7zBJuO2HCLp2Gk=,tag:LgQ281umhlE+UWh/hSKYsA==,type:comment]
directories:
    anime:
        group_order: ENC[AES256_GCM,data:8U4=,iv:9mWJ9meAivHqm7+2R2BWBjEyIf62hrXyuH1Z/bbSZ08=,tag:zsF6flEtzgAkFIIUbAN3rw==,type:int]
        group: ENC[AES256_GCM,data:QtIBgBw=,iv:RLdm4DE3cRi2JsuM7zKL4ytHwG/vDTYcdc4I5qkviNQ=,tag:lcQxlbQDmyedoZbThUdaoQ==,type:str]
        filters:
            - regex: ENC[AES256_GCM,data:KQGFQjuEWT/DI2KPHxKDhkpmnSg=,iv:LMYZSoXWITdLCtwKn8UW9D9V8qAUkKUtKkFhkuPz2GU=,tag:KhCpaJiR+cxCjgvzPbvj5Q==,type:str]
            - any_file_inside_regex: ENC[AES256_GCM,data:tHKe+jqGJL+AVqjZjbN5I1MzYRw=,iv:/couepfaWLTAu1YXXeKDSpMzNvuujllhl8t6P7NktUw=,tag:e/CjRLlO5fmn7b+1LqBwnw==,type:str]
    shows:
        group_order: ENC[AES256_GCM,data:Cfg=,iv:e4ddd0sNYm1g+c3rt3Lb5+aFw/Wu37V2EFX2K95fYwE=,tag:iNQurNvcPglhJmcFIW28EQ==,type:int]
        group: ENC[AES256_GCM,data:jbUhnmo=,iv:enHzC9zhzdm0xDOaXOEnNjezOCtXoNXcJ69SW+lUD40=,tag:kpwaLCLQewDky4pn5XPoww==,type:str]
        filters:
            - has_episodes: ENC[AES256_GCM,data:hpXgmA==,iv:GCzUvTU+GENLq7SejL628Fh2aGQnXBo2ikLsq8p1KCU=,tag:uKRYqco3CB08KXxdxLdrUg==,type:bool]
    movies:
        group_order: ENC[AES256_GCM,data:CWI=,iv:DT/aC+cAH//qjyOD5nf6l2rfmnjEAubDg7w5Ry4DjUs=,tag:I10CdrDG1apLjPOa+AQZ7A==,type:int]
        group: ENC[AES256_GCM,data:8QBtg/c=,iv:iQNxJqIdIc+lXv65Kn4ss8KyukV9Ecv2iG5gkcXIasA=,tag:fi2/Lzws+5HY3QJ/6BCAHA==,type:str]
        only_show_the_biggest_file: ENC[AES256_GCM,data:kMnNMA==,iv:vaxph3w1TmS6bRjOTHyDuOiehtX17OckS9mf6aFQQ3I=,tag:BPUoqwcaoDLhTdhx1qB8vQ==,type:bool]
        filters:
            - regex: ENC[AES256_GCM,data:o9Eg2g==,iv:raew5CSD3hAkap513I3V450wws/jfC0hSPM1OEkh8Tg=,tag:upzKcuV/84Js6Vw3Fk5C+Q==,type:str]
sops:
    age:
        - recipient: age1207u8skz74quhs0xtunrrp2xwj0dtmffllfk7fw93q5eywd7w37qslc9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRWNVMUt4VmwyVkwrSnQ0
            eFJnY3hqcjdrMDhMNGxaN3phTHlXSUJMZ3dRCmY5YWsyNndVdStoNy9oQm9nRzFB
            VWNjbTRqT245dGJLTVhwbXBLeGFkOGcKLS0tIGYwUXJqMmNRalE1cTc2K1R1cG1a
            RWc4NERsajVWWGhsVmhHcUVkeXhybHMK4LmTGTrnd0NzL8az8awUyZeUAq9pI75B
            XMQiz5F89PigokUSj+BqcPjP+zpZX+qVJN8XbBXY6R87YWCm8gPlew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cdr7yexx2vc54q46tkmzw0udh2hynm4dvytjnvzapc64x6rsh59qmemc6g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYjE3QzRwZTQ3d3lsTkRn
            d3JlUDVTWWlEWHVnUXVOcnVaOHJWTCtCNWlVCnZVUHU4ODlERXYxYmZRT2kxZG9q
            eTJkVUlZL0ZyNUpIRWN4eXVXOEhHRkUKLS0tIDg4c240RzRNRjM0aFlPaXpPZFRo
            alRMTWJjdkJzQlY2dzZ3eFA3ODJpeWsKMbpHmSJORGxrxwxroB0LZuO0ZNQON4LZ
            1m8vc4XAb+Py+aX+e1rLkx2/AircsRyAuLxAKZyzKh7O9dUtSYvKcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T10:47:19Z"
    mac: ENC[AES256_GCM,data:5u1zDTEpmerZ1cFZx7W4Czh5jkg8PtzdsUTIr+qA7Qcmj1vOE2Fony70STpRfC4Yqtr6LMUcAMPqKnWUIb7Fz6O4dlI0XsLqJr2yo7L0NZ1JTLYUwpuBBvP+S7ODpkOg2j2eGa6N+gSufDKZQ1wFgk7Ma/gS9LjbvyJhj212Vqs=,iv:VOqcsc9Kwt3E3PwVyZ7h5WEUfkJ4LDrpgykk1AZGsaA=,tag:vOvRTeATHty2sxeUohP6xA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
